<a href="https://colab.research.google.com/github/Abubaker-khilji/Pytorch/blob/main/classes_dataset_and_dataloaders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch as pt
from sklearn.datasets import make_classification

In [3]:
X,y = make_classification(
    n_samples=1000,
    n_features=10,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42)

In [10]:
X = pt.tensor(X,dtype=pt.float32)
y = pt.tensor(y,dtype=pt.long)

<ipython-input-10-1a275b881994>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = pt.tensor(X,dtype=pt.float32)
<ipython-input-10-1a275b881994>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = pt.tensor(y,dtype=pt.long)


In [11]:
X

tensor([[-2.0503e+00,  1.2119e+00, -1.2695e+00,  ..., -3.6928e-01,
         -1.3527e+00,  4.0865e-01],
        [-7.5920e-01, -3.2317e-01, -1.2232e+00,  ..., -5.1864e-01,
         -1.9543e-01, -8.6338e-02],
        [-2.7245e-01, -6.1100e-01, -5.7003e-01,  ..., -1.6217e-03,
         -1.7048e+00, -3.9116e-01],
        ...,
        [-1.0146e+00, -6.3085e-01,  1.6531e+00,  ...,  7.6903e-01,
         -1.7777e+00,  3.9876e-01],
        [ 1.0366e+00, -1.5872e+00,  1.1868e+00,  ...,  6.2353e-01,
          1.3558e+00, -4.2657e-01],
        [-1.8837e+00,  1.4489e-01, -1.3015e+00,  ..., -3.5141e-01,
         -1.3993e+00,  1.5324e+00]])

In [12]:
y

tensor([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
        1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,

In [7]:
X.shape

torch.Size([1000, 10])

In [9]:
y.shape

torch.Size([1000])

In [15]:
from torch.utils.data import Dataset,DataLoader

In [16]:
class customdataset(Dataset):
  def __init__(self, features,labels):
    self.features = features
    self.labels = labels
  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [17]:
dataset = customdataset(X,y)

In [19]:
len(dataset)

1000

In [20]:
dataset[5]

(tensor([ 2.3996, -1.4822,  2.4855,  0.0376,  0.4564,  0.4006,  1.1517, -0.1021,
         -0.3671, -0.7881]),
 tensor(1))

In [22]:
dataloader = DataLoader(dataset,batch_size=4,shuffle=True)

In [23]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)


tensor([[ 3.0785,  0.3504, -2.3505, -0.4828,  0.2267, -1.7812, -0.8443,  0.1025,
         -0.5616, -2.2305],
        [-0.9711, -0.7155,  0.5851, -0.5149,  0.4562, -0.4567,  1.1215, -0.6610,
         -3.0447,  0.3390],
        [ 0.9855, -0.4965, -0.7373, -0.8235,  0.8271, -0.5183, -1.1535,  0.2678,
          0.1580,  1.3253],
        [-0.7664, -0.9078, -1.0569,  1.0306, -1.0919, -0.6578,  1.5193,  0.5108,
          0.8902,  0.8545]])
tensor([1, 0, 1, 0])
--------------------------------------------------
tensor([[-1.0439, -0.0320,  2.1337, -1.1682,  0.8722, -1.0969,  0.0335, -2.2176,
          0.3240,  0.8221],
        [ 0.9759, -0.0193,  1.1237,  1.5884,  0.7654, -0.6850,  0.1016,  1.1672,
          1.0734,  0.8012],
        [-3.6453, -0.4512, -1.7064, -0.4632, -1.8697, -0.4114,  0.5517,  1.2003,
         -0.3885,  1.1539],
        [ 0.8800, -0.6724,  0.8536,  0.4071, -0.7598,  1.9531,  0.3365, -1.5670,
         -0.7100, -0.9949]])
tensor([0, 1, 0, 1])
---------------------------------