<a href="https://colab.research.google.com/github/Abubaker-khilji/Pytorch/blob/main/pytrorch_practice_for_beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
print(torch.cuda.is_available())


False


In [3]:
#using empty
# 2 rows 3 column
a = torch.empty(2,3)

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.6283, 0.8162, 0.0859],
        [0.3312, 0.9254, 0.6723]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.tensor([[2,3,5],[5,5,9]])

tensor([[2, 3, 5],
        [5, 5, 9]])

In [12]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [13]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [3]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tenor Shapes

In [9]:
x = torch.tensor([[2,3,4],[5,6,7]])
x

tensor([[2, 3, 4],
        [5, 6, 7]])

In [8]:
x.shape

torch.Size([2, 3])

In [10]:
torch.empty_like(x)

tensor([[5918328182668266028, 3180215811767039343, 8021511407673548810],
        [7454092237151499381,  732998722818239861, 8462072531373793312]])

In [11]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

## Tensor Data Types

In [13]:
#find data type
x.dtype

torch.int64

In [18]:
# assign data type while creating tensor
torch.tensor([1.0,3.0,4.0],dtype=torch.int32)

tensor([1, 3, 4], dtype=torch.int32)

In [19]:
#using .to() change existingtensor data type
x.to(torch.float32)


tensor([[2., 3., 4.],
        [5., 6., 7.]])

In [20]:
torch.rand(2,31).to(torch.float64)

tensor([[0.3331, 0.7695, 0.7897, 0.1856, 0.4688, 0.3081, 0.0417, 0.1247, 0.6901,
         0.9561, 0.9530, 0.3585, 0.8080, 0.0647, 0.3699, 0.8535, 0.2461, 0.5087,
         0.7114, 0.3361, 0.7449, 0.4312, 0.7248, 0.2472, 0.3715, 0.7421, 0.3646,
         0.7932, 0.0655, 0.5919, 0.6316],
        [0.4935, 0.1251, 0.9091, 0.8040, 0.3543, 0.3301, 0.6113, 0.7476, 0.6056,
         0.7186, 0.6203, 0.4857, 0.6272, 0.7522, 0.4099, 0.9640, 0.3782, 0.1244,
         0.3617, 0.1823, 0.7173, 0.7943, 0.3721, 0.1076, 0.9495, 0.4253, 0.2408,
         0.0836, 0.5717, 0.2351, 0.7425]], dtype=torch.float64)

## Mathematical Operation

In [4]:
x = torch.rand(2,3)
y = torch.rand(2,3)

In [5]:
x+y

tensor([[0.5924, 0.6395, 1.7741],
        [0.4473, 1.1118, 0.5238]])

In [6]:
x-y-2

tensor([[-2.0008, -1.3816, -1.9428],
        [-2.4232, -2.0187, -1.7193]])

In [7]:
x**y

tensor([[0.6967, 0.9951, 0.9271],
        [0.1461, 0.7107, 0.8952]])

In [12]:
## Inplace operation
x = torch.rand(4,3)
y = torch.rand(4,3)

print(x ,"\n",y)

tensor([[0.2588, 0.6771, 0.0300],
        [0.3230, 0.9913, 0.6320],
        [0.2808, 0.3318, 0.1780],
        [0.7200, 0.0758, 0.6893]]) 
 tensor([[0.3154, 0.2913, 0.3245],
        [0.5138, 0.9155, 0.8231],
        [0.3447, 0.8621, 0.6878],
        [0.1629, 0.4513, 0.7088]])


In [13]:
x.add_(y)

tensor([[0.5742, 0.9684, 0.3545],
        [0.8369, 1.9067, 1.4551],
        [0.6255, 1.1939, 0.8658],
        [0.8829, 0.5272, 1.3982]])

In [14]:
y

tensor([[0.3154, 0.2913, 0.3245],
        [0.5138, 0.9155, 0.8231],
        [0.3447, 0.8621, 0.6878],
        [0.1629, 0.4513, 0.7088]])

In [ ]:
#copying A tensor
