<a href="https://colab.research.google.com/github/Abubaker-khilji/Pytorch/blob/main/train_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch as pt
from sklearn.preprocessing import LabelEncoder

In [11]:
file = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')


id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [12]:
file.head()

id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [14]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [15]:
file.shape

(569, 33)

In [16]:
file.drop(columns=['id','Unnamed: 32'],inplace=True)

In [17]:
file.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [18]:
X_test,X_train,y_test,y_train = train_test_split(file.drop(columns=['diagnosis']),file['diagnosis'],test_size=0.2,random_state=42)

In [19]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
X_train

array([[-0.4877952 , -0.25088379, -0.46378664, ..., -0.21989091,
         0.23083947,  0.17173277],
       [ 1.37325734,  0.36318719,  1.29254295, ...,  0.93019499,
        -0.58958803, -0.972629  ],
       [ 0.37225845, -0.05148067,  0.38772954, ...,  0.52157274,
        -0.08280128, -0.21536971],
       ...,
       [-0.76105639, -1.08248546, -0.76208585, ..., -0.30042664,
        -0.3893541 , -0.32657562],
       [ 0.01558068,  1.84511495,  0.00969106, ..., -0.50681802,
        -1.76086788, -0.33345979],
       [ 1.88813896,  2.58607883,  1.79246268, ...,  0.73702811,
        -0.02786985, -0.10998887]])

In [21]:
y_train

204    B
70     M
131    M
431    B
540    B
      ..
486    B
75     M
249    B
238    B
265    M
Name: diagnosis, Length: 114, dtype: object

In [23]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [24]:
y_train

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [36]:
X_train_tensor= pt.from_numpy(X_train)
X_test_tensor= pt.from_numpy(X_test)
y_train_tensor= pt.from_numpy(y_train)
y_test_tensor= pt.from_numpy(y_test)

In [37]:
X_train_tensor

tensor([[-0.4878, -0.2509, -0.4638,  ..., -0.2199,  0.2308,  0.1717],
        [ 1.3733,  0.3632,  1.2925,  ...,  0.9302, -0.5896, -0.9726],
        [ 0.3723, -0.0515,  0.3877,  ...,  0.5216, -0.0828, -0.2154],
        ...,
        [-0.7611, -1.0825, -0.7621,  ..., -0.3004, -0.3894, -0.3266],
        [ 0.0156,  1.8451,  0.0097,  ..., -0.5068, -1.7609, -0.3335],
        [ 1.8881,  2.5861,  1.7925,  ...,  0.7370, -0.0279, -0.1100]],
       dtype=torch.float64)

In [38]:
X_train_tensor.dtype

torch.float64

In [39]:
y_train_tensor.shape

torch.Size([114])

# define the model

In [69]:
class mysimplenn():
  def __init__(self ,x):
    self.weights = pt.rand(x.shape[1],1,dtype=pt.float64,requires_grad=True)
    self.bias = pt.zeros(1,dtype=pt.float64,requires_grad=True)

  def forward(self,x):
    z= pt.matmul(x,self.weights)+self.bias
    y_pred = z.sigmoid()
    return y_pred

  def lossfunc(self,y_pred,y):
    #clamp predcition to avoid log(0)
    epsilon = 1e-7
    y_pred = pt.clamp(y_pred,epsilon,1-epsilon)

    #calculate loss using cross entropy
    loss = (y_train_tensor*pt.log(y_pred))+(1-y_train_tensor)*pt.log(1-y_pred)
    loss = -loss.mean()
    return loss


In [70]:
learning_rate = 0.1
epochs = 25

# training pipeline

In [71]:
model = mysimplenn(X_train_tensor)
model.weights

tensor([[0.4106],
        [0.2705],
        [0.8810],
        [0.3202],
        [0.7540],
        [0.7966],
        [0.5579],
        [0.7270],
        [0.2926],
        [0.0298],
        [0.6113],
        [0.7862],
        [0.3169],
        [0.7558],
        [0.6749],
        [0.7834],
        [0.6513],
        [0.0381],
        [0.5995],
        [0.8729],
        [0.3656],
        [0.2219],
        [0.5026],
        [0.8325],
        [0.4996],
        [0.0573],
        [0.9429],
        [0.3078],
        [0.8346],
        [0.3388]], dtype=torch.float64, requires_grad=True)

In [72]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [81]:
#define loop
for epoch in range(epochs):
# forward pass
   y_pred = model.forward(X_train_tensor)
# loss calculate
   loss = model.lossfunc(y_pred,y_train_tensor)
#backward pass
   loss.backward()
#update weights
   with pt.no_grad():
     model.weights -= learning_rate * model.weights.grad
     model.bias -= learning_rate * model.bias.grad
#zero gradeints
   model.weights.grad.zero_()
   model.bias.grad.zero_()

#print loss in each epoch
   print(f"epoch {epoch + 1}, loss{loss.item()}")

epoch 1, loss0.6697027321469007
epoch 2, loss0.6696531290741736
epoch 3, loss0.6696040172648341
epoch 4, loss0.6695553894295276
epoch 5, loss0.6695072384615297
epoch 6, loss0.6694595574299503
epoch 7, loss0.6694123395732396
epoch 8, loss0.669365578292988
epoch 9, loss0.6693192671480019
epoch 10, loss0.6692733998486425
epoch 11, loss0.6692279702514157
epoch 12, loss0.6691829723537991
epoch 13, loss0.6691384002892968
epoch 14, loss0.6690942483227089
epoch 15, loss0.6690505108456071
epoch 16, loss0.6690071823720042
epoch 17, loss0.6689642575342112
epoch 18, loss0.6689217310788704
epoch 19, loss0.6688795978631591
epoch 20, loss0.6688378528511506
epoch 21, loss0.6687964911103321
epoch 22, loss0.6687555078082661
epoch 23, loss0.6687148982093912
epoch 24, loss0.6686746576719568
epoch 25, loss0.6686347816450826


In [82]:
model.weights

tensor([[-0.0992],
        [-0.0929],
        [ 0.3480],
        [-0.2052],
        [ 0.0501],
        [ 0.1770],
        [-0.1534],
        [ 0.0623],
        [-0.1943],
        [-0.2286],
        [ 0.0213],
        [ 0.1856],
        [-0.2383],
        [ 0.1475],
        [ 0.1115],
        [ 0.0888],
        [ 0.0200],
        [-0.2246],
        [-0.0780],
        [ 0.2057],
        [-0.1545],
        [-0.1548],
        [-0.0053],
        [ 0.2881],
        [-0.0142],
        [-0.4097],
        [ 0.3583],
        [-0.0719],
        [ 0.3011],
        [ 0.0113]], dtype=torch.float64, requires_grad=True)

In [83]:
model.bias

tensor([-0.5026], dtype=torch.float64, requires_grad=True)

# model evaluation

In [87]:
from itertools import accumulate
with pt.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"accuracy {accuracy}")

accuracy 0.6093563437461853


In [86]:
print(y_pred)f

tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      